---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  encryptedData:
    admin-password: AgAlFTA5kumjpf9q3N5hSG1xLjTRBON8ymPeW3v8RQoApuaH33IWo3/V6EeZhpzKp+pThNNInrSuRwgsijO13S7ozGvIh151pVlE/fLHDZU0U8kINxIyWwrJHcM16Xzh+qG7XtWIf06x3MnPTsvNmeMT95YS0Er0J3dB1KaA/3M+YsxzvlEwwh2abUv1CSifVZsBJ9wc+oifuSuqHWwPWw1LuldT1IPm60083p4OnjYqwczoAbrptMYDXdhPhBH0jH1rXgn2Xp9gMWRgRwu6f/GmmS0srMfUL+QMFDL9CfpzV86MD/fWMR8Hxq0YmWr7EM2yf9c9Vr8uzVULleplcyjsojUQtRcWcUMaOwYS5oKa/fYzuGt4WTkZeCka/lSOHkVYVwAy/SKeB9SFDZRuAm0qwqTRvBf1MB/HbFGWBKOw9dv7n+EBi3ac2ryRpkPvQDifJIWIT1eBtW8ilu11KZVg7HDYRbOmI8rOYH7yx4XaahXiHV8gN2K0DmTvltUgBg3c6vi3f36uzxvVToytFxCIg3BSvAzoimv8IC2nAhlOchB7Rinh8NsNw93irfHxn6Z/kL7JChDKUMfH05cE5K+rQlTuFbT1jmu/vukJ1JyynV9LwosdqZSiNx1blUSO72M/iS9eLd2uFYHi/icK4ivTHpiP+CLp4nt8FblH+JwzeqaG6FJexmG9fRELIMJmaKJw51VKzv54IYW8ZN8r1A==
    admin-user: AgAt3UU4IZVg4srDr0BFkPMo9JwBpA+7uDNzpBUEBHFlLrnQLiVy+Ptme+Re0QpcEvsKR/R2Zfj+LhWU3ncZ0aO0Lsysr+1KujLPTvFtgJoGLV0XivQjJnb1ga7bHK9YN0yEjeh1wLTRBLmaM6Sz0qHqM1UmEOirAKYIE4eqvXFwzVHBCr0CDIJFopbsqhllTrgud/pNjuvkygRQf5B07D07Brk1YQyMVeS2tzXFNn5yTyjINNc+wjuRMD5XqPytRfMegmklH1d0Bd92zNG3/Ew0zTOcW1mfVE79D2QRvLo4tSgPcP9a9VuKFgnEMYO5E1E/KPN+LtRu2oOjjJuLj52uIdQt7rAyLmC3UOVEpAe67hhOQzqiaVqnSUOibLGe0w+uk8AwtRZqn4svMWoVsHLnGwFo8dCGycZ8N6zFDAvDRzorXO7IAx4luhZQ1gNH7X2sOVOkWFWpSd2OIpScngRkTDb2nBSHnYdF9a2kBLkod4wVuP+G6hjjiNHlicOo9/E0j9EO4gxTsp6zM4zHH+QYPGxy28zWl/FcXK2pMTXo0uowR6PjtY8wFq+CibVMhLqfc46UDrlggNvyWgQrpCGZSrBiMAR4OyXUAfOp4LIzgntUXc0GtBrmSud33rURuaO35ZQeKWeNhBZtZRad+oN2ZxWPCQG7dEbKE3KqfM+yYgsofAraS7vT7AaU4NX76Wt5Qjx+ZnOM7w==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
