---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack_webhook_url: AgAb9V5+jJ8KGTYEOFhYkz2RmBwLzh9DEb4EyiXIdh+Gz73KGyKYqEQ60af9GMgIvrE42sdCsX8NMldZDcNv2Qb6now2ZmqmFliQ2GDeguGi72LfkXDYFbLezRNbcP/6ofKirP3EdlNQZGJz4lrFLGlfRTXMbla1F6Rbharqy88OmpAyYqeT8jK8VZV+Yvo/r5srldROu6d5d2Iv7pRPjMjdRbRUZRtgVXsiYPgNL22/gd+HYTF2xMCWBmZQ0n9YHZ7lt144dsXeeGFUyiFCCJ4erahWAcbpadEJDLcT2IMFWU5BCNdQSGbhN4BVJ5DCxWjYCojjhzDNwimMMGsnCB84u5CvxycJLvyf/at+qcyjjKOzrblotRqVSiqUZDX3nHNzYF59dJ+WYR/8cePLyJTuOu0CFlKHh988cYdkeJJHXuyoiCmWrblvd9RwyZhFqnYK3U0hAXOyeCYE/dubUYICHrqASxuNRyODa2VAbAs24qBPr0Nh5yXrryVtmkOl7Bevs/jRIAAL0fqUW1nipZtlcDEtxQVGCDk55jsNJZZySJWPVbXlYW/JaPYbxsMbhvwcs55bKa3dCf5owJV0c2RRK65WikXWYc812v+VJnEbv1eN8CprJ7nuEC0iWTd+66qisW+EPPRztGTWyICB6EfkGZzs8GhfD4Ig60Vea77YH0EbbY+v5GYhtl0IcyD09LeV17T5bNdzAObIt+2hnL690VVFxev2g/6XZDmyP2wuvbV+evNJgt8S1mF51ia3okcYkQraSd9+AX8phvZdNz3pzk5KONXBHsEWLJwYYBCZhH8=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: alertmanager-slack-secret
      namespace: monitoring
