apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - strimizi-0.50.0.yaml

namespace: kafka

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: strimzi-cluster-operator
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.safechord.io/role: control-plane
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"