crds:
     upgradeJob:
          # the upgradeJob pod will be scheduled on laptop-agent
          affinity:
               nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                         nodeSelectorTerms:
                              - matchExpressions:
                                     - key: kubernetes.io/hostname
                                       operator: In
                                       values:
                                            - laptop-agent
alertmanager:
     # close the alertmanager
     # enabled: false
     alertmanagerSpec:
          # the alertmanager pod will be scheduled on laptop-agent
          affinity:
               nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                         nodeSelectorTerms:
                              - matchExpressions:
                                     - key: kubernetes.io/hostname
                                       operator: In
                                       values:
                                            - laptop-agent

grafana:
     # the grafana pod will be scheduled on laptop-agent
     affinity:
          nodeAffinity:
               requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                         - matchExpressions:
                                - key: kubernetes.io/hostname
                                  operator: In
                                  values:
                                       - laptop-agent

kube-state-metrics:
     # the kube-state-metrics pod will be scheduled on laptop-agent
     affinity:
          nodeAffinity:
               requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                         - matchExpressions:
                                - key: kubernetes.io/hostname
                                  operator: In
                                  values:
                                       - laptop-agent

prometheus-node-exporter:
     # to aviod node exporter mount the root directory on machines
     hostRootFsMount:
          enabled: false

prometheusOperator:
     # the prometheus pod will be scheduled on laptop-agent
     affinity:
          nodeAffinity:
               requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                         - matchExpressions:
                                - key: kubernetes.io/hostname
                                  operator: In
                                  values:
                                       - laptop-agent

prometheus:
     prometheusSpec:
          # for graceful stop the prometheus pods on laptop-agent
          enableAdminAPI: true
          # the record be reserved in 7 days
          retention: 7d
          # the prometheus pod will be scheduled on laptop-agent
          affinity:
               nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                         nodeSelectorTerms:
                              - matchExpressions:
                                     - key: kubernetes.io/hostname
                                       operator: In
                                       values:
                                            - laptop-agent
          # presistence volume setting
          # storageSpec:
          #      volumeClaimTemplate:
          #           spec:
          #                storageClassName: "manual"
          #                accessModes: ["ReadWriteOnce"]
          #                resources:
          #                     requests:
          #                          storage: 30Gi
