apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    k3han.io/service: postgresql
    argocd.argoproj.io/managed-by: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: chorde
  sources:
    - repoURL: https://github.com/SafeChord/Chorde.git
      targetRevision: feat/gitops-v2-refactor
      ref: chorde-repo
    
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 18.1.8
      helm:
        valueFiles:
          - $chorde-repo/gitops/k3han/manifests/postgresql/values-custom.yaml
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true