---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgredb-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgBdMIMOF7DC9LhkQo6WjLwDlcKeA2sOZUhJve7kU5/+iNxkI2rp+cXKuoDPgRkA2w9yzGSwx8+ccZTjQ91IInWNWHY7lZAz9BqnceFY/X0VqiU5HjiP9ViFFzA9lOpjopGczeDmVG4aq1RKs24p8gvnJ2I8NxWkTIITp0fUTQzvP7+QmgSUGt4Rrob87x0WhdNJa4V/Yr91IH3rtDteASKFL5B4jff8+MStmmxGzPbDum51MEywGUUBRw8lQGYT6zkW7zwTXsiPIJY4t93c2wCMFe6Nb+uehxQWbZ9/vfxTMElUUmIuvmnMWwLfMJ85WQ+shVaAfFdKtAgABH6lyG5I4WRwpe3EsvE3U+EC9PYyqDOctle0kQ8/QvZvUtIqhwtmVPn40sQvYpUSN6QIz6cnYurGof9Wu/FQC1Qs/kR3p/eDylDa/oAFLZg9Gio+H0hYQDUOG8Snc/dvX/V0VVjs5TPYSExxZvA8iTQK65uId4Ed8HOdbFV3rolq4eFNsfQ6pFZ8xFCkkdkGl+OELLQg2dDQROexjZ+KH5St/sm/g7NYwWgz/8rXKq+cIE+AYDbEw+1euH5D9q4BkkLtiS9u0z96+MmDMhA4V2F6OTFXZj+I853ENUQ6BAPye4e0fmFvXIOBaDP1M8LTYViaIfgraCKisNXAmb2dTegZEU3lJVFW92cnhm5ZRiU7u+aqnXEYCQLfA/MttP9T
    replication-password: AgAICuj+UMU1DowgoeGUFrU+7i1t0QospNwhzopRgQsYJ+K9la3VQF6fQmmQ/AoQj+I6u62ZjSrdyxzzjhd9V4eUzTdBVbIk/W5RQh0VILwBFFawJMKQGkirJPDKOK3SvP4TK/uOPIS0rDEUG0+bSxMhl4+zJSknZznimuT9l9o6yE5Dz4jC4O1c1++YVgEBuKjJkGWU/8tLQANTIoilFgIS1FCHuYlPo3xwqxMUP8+QPG7wCxwGSCa/IEKwF3mO7yP7WxP1wTkb2nmtnCfg71oLFFexcrD9PITu62oUL1Y3uTIi//l+E5Ruxc6e8mga2il9OtkYn+N+B0fmXu+Ep8UE+XTDRLNws/mnn4fWEWlQbvqaQ6j2rHOVdqXiaH1ebrj2HZI9B0Gj4w4+5TUCBuieiYzUqZD77juiSbMqV0prVi6x3olTT8H8INKBym+wTkRncZW0IVHSmLKDlaTUmE1s77GxCB2Kf8PjHYMbzzbVWz6Ydr5cBtjzUZLBIP7IxCdJyrq3KPC9haygKAGklWep5kS+f3rWFp/SGZ2WVw/YeDhl3LS30JmKl+sf5E7IWeUVy8dO9h/On34/AUK1NAKN2VjCf9LqdSx+6ZLczZKx2mm18vY15x0DB0YdCDXtWYCZAt1ipOOHRdiC82sjBzXHFhLclEOfFORAK9/NXCrGWahWrsYfsX9rngQyRyhVaCdv9m3SyQZQjDtd
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: postgredb-secret
      namespace: database
