apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k3han-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - service: cnpg-operator
            wave: "-1"
            ssa: "true"
          - service: strimzi-operator
            wave: "-1"
            ssa: "true"
          - service: ingress-private
            wave: "1"               
          - service: ingress-public
            wave: "1"              
          - service: cnpg-postgresql
            wave: "1"
          - service: valkey
            wave: "1"
  template:
    metadata:
      name: 'infra-{{service}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
      labels:
        k3han.io/stage: infra
        k3han.io/service: '{{service}}'
        argocd.argoproj.io/managed-by: applicationSet
    spec:
      project: chorde
      source:
        repoURL: https://github.com/SafeChord/Chorde.git
        targetRevision: feat/gitops-v2-refactor
        path: 'gitops/k3han/manifests/{{service}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply={{ default "false" .ssa }}
