apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k3han-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - service: prometheus
            wave: "1"               
            stage: serive
          - service: loki
            wave: "1"
            stage: service
          - service: system-upgrade-plan
            wave: "1"
            stage: service
  template:
    metadata:
      name: 'infra-{{service}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
      labels:
        k3han.chorde.io/stage: '{{stage}}'
        k3han.chorde.io/service: '{{service}}'
        k3han.chorde.io/managed-by: applicationset
    spec:
      project: chorde
      source:
        repoURL: https://github.com/SafeChord/Chorde.git
        targetRevision: feat/gitops-v2-refactor
        path: 'gitops/k3han/manifests/{{service}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true