apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rebodutch/Chorde.git
    targetRevision: main
    path: gitops/base/keda/charts/keda
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-addons
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true