install/%:
	bash scripts/upgrade.sh $*
	@echo "[INFO] Installed or upgraded $* successfully!"

upgrade/%:
	bash scripts/upgrade.sh $*
	@echo "[INFO] Upgraded $* successfully!"

uninstall/%:
	bash scripts/uninstall.sh $*
	@echo "[INFO] Uninstalled $* successfully!"
