controller:
  type: daemonset
  nodeSelector:
    chorde.io/tier: medium
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule

alloy:
  mounts:
    varlog: true
    dockercontainers: true
  configMap:
    create: true
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.relabel.pod_logs.receiver]
      }

      loki.relabel "pod_logs" {
        forward_to = [loki.write.local.receiver]

        rule {
          source_labels = ["__meta_kubernetes_pod_node_name"]
          action = "keep"
          regex  = env("HOSTNAME")
        }

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }
      }

      loki.write "local" {
        endpoint {
          url = "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
        }
      }

ingress:
  enabled: false
