---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgChIV7iX1dn53Jc2vn4q3Fa2C9wVANd1OsYjLmBL8Q+Rv+IZ7YpbbCBHm07ELIQwDXwANIO0dUmVUITFvYPAnfL3D0jkYgtmV038Oi9BjFKpSlrzw88UF1wNHljB8TAMwfnXPUMAN9llhkiEC67LBk6gwggcrG8rS6uMMgInP4AA08ISmU/x6dbBDTYFeRQzAgKyzop5rMSW64lnFRbpH1ORHy+lXkiHK5g7i/WDSw8/xYtowqLkBihK4KVMfmct0y2dkLRujGg9sP1UwkE3YOhtlmlHW/BLpir9vFgB68wtBmn+cY0SDogTLBQkwX2o5l+Sv3GtjXsoBPxk8+TMoAFCcGmx1AFxDAD6pqO09sa9W9ZrJn3vHBAdRHxwu4RjEWKKnMHkNy59j2cLJBvch6CPIeLxYz8MhJuWWmS4HnqEol4s9sTLjCj237G0qxqBn7s0PaYcgEqSnREs04XzN8d/npVux50QneuTMuwIZtCWUkzjCbtTxRNkoHO4z6aU6QHLucSVTIlT7hKa5vp16mD49yCQlxTlqd8TpwdBMpZNLiuhV3FOjf4JZlEl7HSyx8Nrf9qqREVY5ouMoARXb7gTbDu71EnTPwO4YOwPMrU/J8/e+cv8Miu/h4veAwu5X/67Lye4googfUqq2kIgzJSTD93kPSyyXmSE/6+P7VIpD0XLUTkn6UNRoyk4MvZ67HX35E1WJ4PWQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: database
