---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    redis-password: AgAeZPBUkgX70cNs8HSoGC4r9QSfdgMDbtYp8zAlz4tNSZwPGUd7AjZNjAapMW+33MHMjAW2U+ATmopd+MlIJ0HowpbfAHF7mSyaFKf9zzDhFSO9BC34/Rut3yJlqSjpM9PSeJcHkXVG4hxM5nRf1b4wutZk2EsoJVYN5y+NJawAkg8FLa8wVfZU4FIthsnCAOUlFOih1eCO/lfZbQUu+Sul0wajxrgjM3gUKpvh2LRQyqv+KfR5m7sysSxLYOtAB9B5u1U49HYcjzaywnTe3roVbrx1/xXHmkjMCnHjsM51qdaWSGODHyYDRwnzmJF1vKk2sS2OLXU0tqgnxq5VPYrs8Hu34fS2hQY0loUL4l99aR0X1LC78RmYUbQYTnEsCQUATA1J2p5fGBpFCJHNfO3T+Ege3Kl7MyymiQtwWjOWCpc2nCNEBTECFxMIXmpczwU4RovDPaZ0dxHe6pkwM7DJShhu7vc2cTx6i12CIOlc2eohj9zmRSDSsbsPscFmvuZwzTTHezqxYw+rMu5l1+lUnRPPWzPe1VDvEQUvGeGiXJ4QwX6w1znnwxE/kk88uvCjBNYbXUyaMMg9KcEGx9PVd47eBpMpLWugp0PVeoa+p9qYplkBNfDSauQkz6gAF+zRKelItHCklLp1llFykk3de7tTOFe9w/gZx31RxtdZyXEPPdlaeSETvWyqg16D1SYxC4lflNJ5hjYo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: redis
        app.kubernetes.io/name: redis
      name: redis-secret
      namespace: database
