apiVersion: v1
kind: PersistentVolume
metadata:
  name: acer-local-1g-valkey
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  claimRef:
    namespace: redis
    name: data-valkey-0
  local:
    path: /mnt/k3han-pv/valkey
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - acer-agent
