---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBNONVh5k4qsDfU0Y8qKNygnD7bPQoXP0PtM9j+cVbuhM3PhhMnN1cn7sOa3scyZObc0S2AJt1PkUuNZmE7K1f4UpG/+nKWKe/C7DV/8HVWN57DRodT9RLvuyJnvLIadxUFywWmEpL0LMs0j/ps71m2xNyoR6SHPGn0PwmiSM2fyBeev3nf0yY5IQOVAryoanBIA8RvCpipuapv4AOZuZOnf1JYQV0DtwO+D7mACHyKx9Txi8u6md82WkleXJLwxZm0EH5q6AmjTr1lcQ9gLroEAYEStt0jxv+1N5PBGbd+v0CxPFAjgXWEhAuUF+OxOhaDtjmFcjIbi+Rznl/V7JAUZpIYwnkiHa99/96xOSVRrNL6yKS+oqi4a171MhykzXc/Fp10lcXkRgqjnQppsCHZBRlKsn7TIgjoaA9XpT4NpLOgrMKKfwHWpjFu3QZFLS4tFwY4MFNKm7LnGJYrZeIOFr2Fx6OGE+DM0uOdAKyvWL0Zw4MWq0mW2MYRPeDDbVSun05MWPf0uX5U1D1t/k7O90W6V3G+ODMbXz/CrFaGvBYY8qYz+FvfnRNpxgIMcpFDrY2l5rCbiqufEiEwzQ3gCJBzMem/8LzWYKuNC2WW5HiT0WSKVAj2za/OGuS2/i09M4yvFlnYS3daBhD632fRrGngAODvJB/TvakgVCE9YpvpLGQoqTPUBYXwQ9eYrFy+/GCWPIjOdm/9
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: redis-secret
      namespace: redis
