apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: redis
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey-primary
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: valkey
      protocol: TCP
      name: valkey
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey-primary
