---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-secret
  namespace: loki
spec:
  encryptedData:
    s3_access_key: AgA0MBmm0klWcrNIqj78/lElaRAaE7f0+0ptTRQtvtGZjOsZTJP/7xONdTCH3yQCBHFVqKP4LHzFtlE3l89j/quo/z1pilJP+sn6nB3OHVnT1AO0MolZv9FhB+r1aciiHZ7UpUb0+3WukSctz9pwVKZYctObzYf+na+/TKVTsJ7rDtx1y7bOAmSdEjOjVeShZqyEH7l9s9c26djnLgQ35g23sGotyhqiDwdwSAclBxpDw4u68g5kvPevZAT2wEyUuXyL2fWS63bh16M8PKYbf11bnTWR/1eZDd70q9A3588bmfLe09D787Phih674njHQa1gqOu5np2hadQckKaWAmoDrX/g8bVknkYAiLVpPsreTjm6uzTsU33RGXIXVh0Yzr8rlmGTdpqAdNILjOk3kp6kAaEfcRIkpBj9k0cpWce72hu0knA1aOdFRZnmFu6sDWfGEl8nar2iEJX5vqh2jd9NJe/6mpA6zlyYMHFqWzDLmKWHbeicjY6neZIfbxBZBntTLlZCh9CaHnbkNVVTqO1wOMJnenQGZ9f9imRtMTzNdEvZ7aUMnY3nKQJ1YLk4k6W5QdMkZZYc3g/73DBGqW/ouMcDphzk3z11HHuZzfZQoL0Nsn+lsFsS0GGciqnxcBfFmIu+1KWNQwDhXp73VMRP3AFgV37G3VUtGla1iczZbXcqeuiGuYTbiqNi0K2BPBgc47+bMfj4KTTG/vfl4zK/T4oaLA==
    s3_secret_key: AgCgqznbVreLIanYyoOzjVXdcjeNz92W9O91P6XWOLjgsXuV73eKtWn+LRY92AciY0gNap1+h3Ya3hamwnKZom1GjRHEE6sVT5Y8l4f1gYCiAyrPEqSDUkJdZou6kALvy39t1FxDsnVBf+ILB0Lgr8wMQlNV+0tsY2uA1/Ji9+MKbsQ3o5wuKegOme/xWxGd5/rckscFvw31aWobQIXgoSS4yTBJ/S1kLI3fBuDil3FIZD/1097c/VuMoEyiK90JWl4qY5k2LkVy7GmAD1Uo5l9XEW4j5ayn71b8f0gREF3Vh2iNTvgqGEWya3WUpOBl/4VHZqIkxf32i5EYChwYIK1gIeVLv2kNIbcJ0z8FvZhNANsPIdBc6GWsUhBRT2reOtLCnudco/K7PvznrS+uZ3IaJDkRBQX3o+QwcPB79SQ5zW8RBMyMXfROX1C9KJeZ/F4zT4efNgk+lmmQqOktN3wejuVkt2FdcJjFoLstPX9luQSFufEdr9qURD6ertI8/xB3OVxdCrtlgN9NZUNdOgZtQ9PyzIWThlXtWU/Q5esQaNFpoFHMlfUAxoZzoRpxGLBPQeIl2Dq/DRcAsmfA22/TBFiUOmHdEe5qqfTgMGxiZ9h1Rp2NFNln7/48kMKUYiOcea6nSyqkJHiqm9AtsXNzhQwc/WW8F9JHZA1A9tZVjmIkbJdMp1nMDRT8OlGsReE3XfJcOKGTPxN4ggLb+jsv2nHquU+gZMJ8cHx27/YpsY8pUnqoXQ/0
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: s3-secret
      namespace: loki
