apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: chorde
  labels: 
    - ops
    - prometheus
    - middle
  source:
    repoURL: https://github.com/rebodutch/Chorde.git
    targetRevision: feat/gitops-v2-refactor
    path: gitops/k3han/manifests/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
