config:
  clients:
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 300Mi

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: chorde.io/purpose
    operator: Equal
    value: proxy-only            
    effect: NoSchedule
