apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-public
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: chorde
  sources:
    - repoURL: https://github.com/SafeChord/Chorde.git
      targetRevision: feat/gitops-v2-refactor
      ref: chorde-repo
    
    - repoURL: https://ingress-nginx.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.14.1
      helm:
        valueFiles:
          - $chorde-repo/gitops/k3han/manifests/ingress-public/values-custom.yaml
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true