apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    k3han.io/service: argocd
    argocd.argoproj.io/managed-by: application
spec:
  project: chorde
  sources:
    - repoURL: https://github.com/SafeChord/Chorde.git
      targetRevision: feat/gitops-v2-refactor
      ref: chorde-repo
    
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.0.6
      helm:
        valueFiles:
          - $chorde-repo/gitops/k3han/manifests/argocd/values-custom.yaml
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true