apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-primary
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1 
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/tier
                operator: In
                values:
                  - medium
              - key: chorde.io/provider
                operator: NotIn
                values:
                  - local
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

  storage:
    size: 10Gi
    storageClass: local-path

  bootstrap:
    initdb:
      owner: postgres
      secret:
        name: postgresql-secret 
  
  postgresql:
    pg_hba:
      # 1. 允許 streaming_replica 這個人連進來做 replication (同步)
      # 這裡我們用 '0.0.0.0/0' 是因為你的 Pod IP 會隨跨國隧道變動
      - host  replication  postgres  0.0.0.0/0  scram-sha-256
      
      # 2. 允許 streaming_replica 連進 postgres 庫 (握手用)
      - host  postgres     postgres  0.0.0.0/0  scram-sha-256