apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-primary
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1 
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/tier
                operator: In
                values:
                  - medium
              - key: chorde.io/provider
                operator: NotIn
                values:
                  - local
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

  storage:
    size: 10Gi
    storageClass: local-path

  bootstrap:
    initdb:
      owner: postgres
      secret:
        name: postgresql-secret 