---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgCoJf6iOuxY2qB2E0x11dSO3MpTgysZZyYxamRFtpQ/fpLXztTH8Mbs5Xhd82m8LfU/uoEmlBjwAPB9kGRKwFEMbfqPOmNxmNXYoMmr6R4TpDFTyHFbdANXDuuCwwUZ8aKxcrpnA15PAfm2SDgPjiBkTLvnh4tHp9sSYSUPul86pmjb9ztquvxyb7jN8kJOFtNyPOtjAWgsIsmG233hqhI+4dzKX823TBZcZtxoa83+z4+z6h4mZGNLCIr1kVV7hl6zHApBB+m+BaA8Nyxwzfmce/g352S+OqdmoRc1mUtXZGkirDs+rutDKIMj9KM7Ar5T9NbmNG67vrxzlxg7sTf1JteZvN0ozdrxSS30R/c6SwH0TJK4yncYpd8HcEj1Q8ba1YRZeMRqHOO8E0C1Ehs19EhzAbl2jSeSifhbQqCtcD3SenD8aNdJI+WpVzg38DAFpJ2IwlXZmqSUMcEadbqv/ElGWdv5oiV/F3mDLmUJGe1AZHoPEWj8NJno/7Tp/5YawWMRw17vtr1PAjZRW0Rx+CEmVfrHMxLFmZHLWfDwjuWGCvZ4vu0gnHViKplmjgkPA8UrrqvFFue0RshZq4XmpplsyhoJ5qc+jNm6LatF53q8FJTcATxd20cs3JMYbfzMqGiT5qGZsgJog2VyRbcC1xmSWwLXVuxa75lA+v7TjIVAi6KcgH8ytDgE4qpFOMMb/CzCCwie7L33
    replication-password: AgCuy9hosbuWF/MRLfJMJknV36x1lxLSs1rMB3gpHkd5kGbJlamCmNN+2QM2BtqQxtRe3j4NJqQ5iKUh7jHyNdUnbg0J50hYs4XCg3im0VDjiVzRpk3MqBY3cSIKGJy1guBm4lfd3a10oTPxSIiDR/N3OCf5QvBaC+9EJQVNlqWBd70xjnxbknScy6zGrbZUHJuAH/uNfElOimL9mD58+1nKAUO8pjc5jatrdoMS/onP7N6mTcO09oB1+1jhZtNsB0PSBXrfF7KKbVDiqS8+Hq0ys7Osm72r3c6b02Xd1vZjc4FgyYKPyhy4rkl23b6jdYxTaE9MpkS/HhmkdC65fK6PQ/h8S2UYTX5UlvjtvOzTY7PQIwk+0Lqx+uMi2z7oNC7190BQzaGEzpvkvlnqOnpmnq7bzOZKAkcKPtHgJg9hBTyZfwvDbi06dm6UcO2YSqvTKfCgJcm4Y3PxTtUkvVaZXhBE6q3DiGJ/oUfp25wp9558ZzcGCihGzKEPzCGvNwIcVTtIrKEz1AisL03JvFcCAyBJgGKc6fqncxzinJLMhkeF0PZ+MGWHxokfmHc1b8XDuBI/mE6n9p3WgsfJII/rT1azjOFb0gaLckIVnGqKM15Gt2UfLDSRA/rZz+GveWT0URfo8OBHoPD4agciRZZZif5i130YNnJfdX3nVKbLslHAPugRYFjXWogmE7b1L0XN6IixtkQogMs4
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: postgresql-secret
      namespace: database
