---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: database
spec:
  encryptedData:
    password: AgBEYkkEAH3xnUVUfat94stAnx0dByTqPmnqVAEx6D3oX5hrDAWsAHsH521uP7vEQuLzShZ6rJkKtCXuUzE6QRYyvo1w20pYYErIcXpJ78Kj1n/Q9Qwrbn7qTXCeNdn81KppmQ15YIFr+j99aNBU0KicbCV0kE7sSxXKnF0V2glp5OGzND2HldkxTCKV1XhdyLMP0k3e8/Z00oZcRNsp6rLocKxIp6HkuDK2p9pbeaU53r/Ptqe98mOlM3SyFlfUYjMSiJ3kc4DKkSt3qajdFwiFvW/bJGkDzfhDohQUvq4dx69/uaR93GLWyteL8DPrsTJO+DCzhfgXnfo1dBdD1IoWgyX0G/mvXd4WttceO55lTEUgKBxrD3/wkSyYQ7bOOMl2/tw1rS0vxQdBde9MGdYSHTzEszWvd5CJi4Q/fh99djZk3U/YyNYQoix7uZylT53hz24Oh0TY0ODPtfD+bh3DRM1c49GajzT8aEjIVnLyS4FMLMhUWUYHZMsWGXgFtQQYIoQC/INcwZhWOW2sR1vDSQQ8IStjhnqoiuka6SJtUIDQ3+rUt7n6QB3yVFRCJ7Oua4TOeNuGTbTkDOGkIOkLS4+E2qpfYTRY6beIIDnB0aQvQ03S+Z+J38WlZjgMwlSyhmF2oMQGtewjLhWWwmjRhOyrxlFFt1S/OEUYirZL70/GuXeUDESp+k+Cq2G50wvUlHztjkUHyL3R
    username: AgAKXDPCJRpDL+qnkurpKn1mNQkAvR9XW929prBMjuAmeAX+TwJVuIRRDer2BJlwa65zOZlKT7TyVOwXa/sPGDHNEDQsChsHfz1GkgeMK3LDYJ4FEHQKiawIeIWQuwCa/0MOxHVZrRcyiI74rKS+abIshIkBrM1m/h78uHOQUE6XqKlXTfJYrEVRSVwaEXO3b2ak/dUB9NXkMc6uLjJwSoyqwa1ON6CMiYTaHTnWFS1z5zm6IYEpMChlGf4K68M9sPf1q0KIjeRG/cHbm+KK44wfiiG7Hc+VbRJstyWit4msbBBtsaNnss2P2J+RAI54AjWokpzf4WSekMYjnj/A0DEHAhNtAHCATIzV70vHKgVDCgIocIu6/lRSG6QMCb79txQJJD0Vn8HAxjH94Z1ibvKv34RV0m800nHu9XVrkFqDIxIzTNhEPQaEFw6i3AMUZ9Ll9gLYeZm6malmwwc0QtZSdMNTdgrWwxVxhz6dWc6tvhl8lZvCNuatMb8ViDjCM9mC7Fc1smPoSn3VhiqqZNYnSxOjOP6JUy7Ljx1GpncDK+Sq2ewswsDKp9pD+RJqt1uSiRLEMrm972AgND0Tdo6+C8vfn7IICHe0vsy23I9y3uKAeNbKtp8G5iFySCxHmFMw0sp3R4LCdtU7WOqD9Z1gyH9V9qKFSWjPTCjtR2MAZlQfTQypnq3Q/UxfXiYMkMWOsPA4j89hWg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: postgresql-secret
      namespace: database
