apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-public
  namespace: testing
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: echo-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    argocd.argoproj.io/sync-wave: "2"
spec:
  tls:
    - hosts:
        - "www.omh.idv.tw"
      secretName: cloudflare-origin-cert
  rules:
    - host: "www.omh.idv.tw"
      http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
