---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: echo-auth
  namespace: testing
spec:
  encryptedData:
    auth: AgANkQw6KbeataZzQlzxty8RGB/zaqVa00zWrboNVQZfQh5aRB45L3BD9KzuBJELJMMQPrGky7yc2lTp2ykHpdTywkTu7EcUY5MRiry41ynNk4YXr7/Nv+3KKyZHf6fI9gJjh8Srapz/yzx8H/9XBXf7xlQwltujVjJwHQ2wLb7kGMm3Aa8zKU0vTKhX1CEZEqzDEwpnn8zWDl8Otl01upoN3AMjKFF2TszQZWCnCvE/bc5JlAfjOWMAI3Y/aMgDdBCxqd5/9H1zFAo0/pjBca/NHGQ6OpurlBjR5K/Hssz1vp1h/4kVemzQDF0GV79p+Bq5Pf9Yw+Vb0aQml1IiPS413XyUdA2aqpKopKqblwcEuXFYIsfo6WJm/mxhHt/vJk7Bq61oZaX7y0qICXK8X1hKzAYe8Gm5jD+ORQUBi/v09yGK64kSRD00B1rK/BB5Nz81dQ5hBgdVk06mL9nfm3cFQvJs7qD0SFuqbl6pU6erdPhUeLa8QU+Fkr/Il+5qJQ4NNy0nW8BBaX+jQGFmTgZGm1dwPMaPaXJGEGIzTMsVwjAGIxN8XT8Cct1qeW1KS77c6qgeRyu53Y2+dQ5Flg2thlJlYtKB6pyDQjzyjQKiWnxILR+m/OsEJTNNsvpYqv9w1MJA3qzs6jwoG8ATJnyvTpCZWeYjBg6w/9i4HkELmNP5dyG6dIAHGX5omCDpxMAqdByY1I3z8Ba7WzKNI+uRsuODZuXQJP7aGmWAbyuQ69zWRGIJ2elxQmbOdqUMYWeY98NjGgL9Gi6mvgUYO9GOmKAdBPOu
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: echo-auth
      namespace: testing
    type: Opaque
