---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: echo-htpasswd
  namespace: testing
spec:
  encryptedData:
    auth: AgBIkAh+XIVo8nBlOsik6n7IEfeHlxQDN6nL5rQeCboFAK3M71ZF2vg9fVB2K2SfXz3nseNYAgSpVIKBgel1rMVwrlybJgt3R/9qflmdGEGi/8clMvJ2R38BVOu87EWqaS0dwP3z3T9k1CNFXNA1UqBHwrCxXTVZe9ra1364qXGujHc28UQWR6TbhNH8cPJa9TtX75trSj14vJOov+uRrtoWMJ1/3X3Gg784z17LvSL+Bup1z9d++3A1M/wf/f4D5eu4krBc/oYi8IrzQRz+N4//PbbjIjvSsqW0SdOYOyTpPkJFwltQ27nGnOGIIZ1DMR7cyhvtYVwn6nT05lr7d/JkXxyObNTiak7ql9JRwj6paFY4OJgrsEdvCJcwIS5uoV7prPMUnYAZBLu6LRwz1iMZzKzaBVBvDG0KfiESySpt9E+twvmoAUas2SdX2dRBWS2FyByCQuD4pgs6FNnVCN6T4REX83qf0Jgbs6TDQfkDAMwe73k7zQGAeps2fJkt2FlWZxNvnj77o1aTszxFSwU83v09QB4jtK+Wy8A6ocJQm6LPOQ5Ot4LK88wd+Q0xKaH/8NHjWKrCE+MTeag/Vt3b/LF8R6PPUGF/mnenmYUuxR/7peHSYOlc7KwxtOdZc94wEk8Nal4QjYwhAlcmQFIRud0qwptj063nhILq5onBuX9e5hAZEWiifvSJZhq31kqT6yXGyRg/5oP3DRwMllVKoJEH6MiSJphploTwWi92s22E7W4jXYv2wPSakVpC
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: echo-htpasswd
      namespace: testing
    type: nginx.org/htpasswd
