---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgredb-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgCygjSshIHUeGX4Zl+gsCB4NqcXeIBu9dL0gqKM8PxxzVdN/3a7dOweNLhUfxhF6QZDtA4X2WmuQsCDWVvntNGgbzFkiFjuaC9M2PZnj8dh+JvHNgA6a3lPKS1u7pVLWBReRb60CaqPWfCaefVdz0z7kk5wHcXD+r4VPSUv4lbvWBU7goJ1eB1U90fV8H3jNIzfT/WxUIuSACxzI1rOMJcg9OOxMsHG1mv/hnBDQJKeoWIxUhWzRU7A+31iwn9r4Az9WM+MoOc0WE1tKxqskZkBMoPOpVtQt5VIIQaIrlcJB3Y8Ea4UA0n6HJdfQzODj4kvAEBPwRxAiWvWZQaL4YEi/Qb9mNN9ijW9rHhBUCiUe8R1iTyRUI18ef4na+84/kIE1sWpUatCT6I1wE1+jBqrnTIukXGaBnaYDcP3Nt9LFm5aSnjys6Waw4MOTl5UQ/nLvoDNLb8f4iLM7HvE8TIPJLlDBaSfd61HAKF33ebRnE6NE04rLybFETdJuH9cwdtCo+F7tzsCyHUWkMH+sAKgAzX4ug604yNsKfbp0TgtepZWxzEthVPIQGqSdQumz5gfndZXlB2f6Gvr4ZXGE98yQOZXeCY0hw7tATNTAIZmcrCHMs8smOV4kias6kGCXGJmoocTawqxr5Qus2MS468ADNZC2dpBYGQhoFf7Oi5a3Rxe7nNkEss8RMpftB2/WdWUBkYmd3ubGtr1
    replication-password: AgCRj6hjhO/liMEomXdG2Me3huNhc2Ga1WFvRSNZ0X1wvSWeFJwwVPiBTxvfNTZpf0mCALmiAU9/UPCHPqc388/eWxpFgvrvETEOZofZC8UW/sgYtBcbTMAdEABg4m9PvVnWGtk3LVx7bTeAMg1mbZRhokhmSZt2/SgGXHLSiaoWvCRGFdoYQ0wlSat6HpvI8pHcCqjfEG3qQfbqsu5YtBG8OiAGZd9WZrjY6e5YiAXGxBg/zqKatQcRcWY7wBOU5T1cFup85fYjCToIeR4LxWOqhub3p9ezLjw2P9en+kHuTG1IUfXO9LFfx3sibviwWLnlh1Hcz2qPEjWzDD77xCInRoSlHqoPZhgkrIdAj7TjGebvYy+FLQvXwmiLqxh5z48C8E+hpNfhT+Tny4DwsAFhx1BUoYoqhMI5Jesqb1FmEHTAQ4+vDOjMl9tgC7DHWQkvd/urJyMqhW3uxmmi7/y1QnqeyW+HkYbiGMdul149OWqzJWjuydhuix1uNahXBbOEwjPVAQ4xyw0JFxaSggfzbSTQip1ZKx/aB7FidtjpoAMxQWwW1QPB2cHmdHjnKyDOqUHmgoJkLrfbHdtFRAVljCaZmXwT5ySTk/XmY2JnUVYvHMlwPbVs5gYFxv180ihjpnvhkTEDJz1DIkNmRjGSLaqF2m/5gzkBJoaMA4VZ5xXy0N45G40rvlqPAeFd8NT7X24G5LOiQA7F
  template:
    metadata:
      creationTimestamp: null
      name: postgredb-secret
      namespace: database
