apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgredb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path 
  local:
    path: /mnt/k3han-pv/postgredb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists