# tou have to change architecture to replication if you want at least one replica
# standlone or replication
architecture: replication

primary:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: tier
                operator: In
                values:
                  - medium
              - key: provider
                operator: NotIn
                values:
                  - local
  persistence:
    enabled: true
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

readReplicas:
  enabled: true
  replicaCount: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: tier
                operator: In
                values:
                  - medium
              - key: region
                operator: In
                values:
                  - tw
# if no user be set, the default user (postgres) will be used
auth:
  existingSecret: postgredb-secret
