---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBpeJ7atE47EfI0aqsc1OPHryjyIps4J6MwWa3oGLs9kVqmlBDBgXKqMKGgrV1DmqQVtAlRbi3MmNKgre9eHaOiQhvFCkUJ5JIEZnlK9sar2JHauf7uS1dxEYJU1WEvYeUO52+wy808ZkW8a/1Uw2gPHl/WMriCcFjDUHK7je4Ep0dP0cqBJAJjPGecew6bOWYJrjs/c2UKeSwjX7g2RDr7Toyv34MdJRbYlMbUvMAG5SFMwwzdZ0DiJAPtKpbP1XPo0Uh4lvsfKXWyGsclhY2heBYU3rau/d2DwZ1kqCUHn1u4CSJHMDPr2jJQUALDC0299qsdX0QfrPBdKAuAHjcQeUtoufi05KlqzxW83vUMHlImix1LjeiAdddjggjJFCynpjpwGJV+pvVOSi61Lp6lEWksSuj2sNw/RgytkmY9rYQyy9Sii8+Hwm94yC59iwp1CDJ1AYxgRH3RHxyR9sQX6Z2pqh80/iWw3US4cIyLLlBvTetEmVejO+oBK9rIjBC/fJRfEW8BNgwBIFImvTAA1ACA14yg8hRgeIeAFQpJpWH3DnmGWolEULsFN3DlO0lrVvWoUkGULLRpx1k+p1yYpVHeTUA7kKYXkMqOfyh749cgefltG7/C+ueCYBp43A54Jn14QCYgMnRSe+kX6r0rCI0LsWTEq4TJCmrquUxcDc/6p9azb07NfLG4aiiyAiy03BKiowDh7KDsXt1X96F+pkbJP01X6wiUPg6PaKBzOzwClwZzl7YfFxdXApXhJ7Z1vffY8sZmZWDPRcyrT49a3ihymMaelkLiEmUwPL2oLTvLoKkCDvgqLmK4aG3LUmxE+1+4v5fYgmXsGRjbrtmk2F96Dur8mqKYyDxJYpNVnoBB2EgUIn85YLdyJM4X0W4SDX9vc9OgaVaWjm+Ibwp2IzQtvyDSGIoiADp2TLjBS9VMBzlgRC3s
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
    type: Opaque
