apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: chorde
  sources:
    - repoURL: https://github.com/SafeChord/Chorde.git
      targetRevision: feat/gitops-v2-refactor
      ref: chorde-repo
    
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 23.2.12
      helm:
        valueFiles:
          - $chorde-repo/gitops/k3han/manifests/redis/values-custom.yaml
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true