---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBmqeWoP3c5mvZjgr/2tX5zBOmyvSApqlsfK9dtepE5MIJw4kxhLqzub4AOeYJRmE9dTRIY1wYwaVA+UdyOJ15f/AlZE1fEH/Qh62Gv6By63gxohnpGpX4RhTifxL/3X1Y/T/EU8jpB4PYvwl/PfMvfpAjSSm9sJYilhNx1AYpnMY60St2SxPGsIm2ihqZFaV1z4Q73ekqGNhUTCHQoP+vU4Rq5KRU0op9P1sWw7xwg20BtKgX4cabqaktB3EAadg21nsgq2xs/UdN1Pf/j9G1lictM4RqNzU1Kww2KAJZ5CzClP1KTONzSfSdlSIfeJefrbDq1olB3YR9EAKJK2xCSsgsonb/p7zCNpl5sZ1ACMjAlCKR/UgsCINH9pCWg1Znefj/uDi5hSJQApYkdrfRuW64Sk4UNSp6oV6Wn6iezCjMMq43F0bwKKsulWQHQDvAI6ryYgEJXd3kfEYDFh7ON9JZZgLArAtwnZhbp14pGNOWJVKJ4u/z76Eqa1nKawrFKDnZNWsZCsaSAyn7Q5im+eumJfBelXTRuYT2d+ffq8YCfVzfJfkdOzuas73+aifY8OM3Jtk74TTUIvXJrp99G+N4H147DnZQp6OR7Ib961LVoP1MZL1bUwQ/WausSBQxQL6Ft5TyFUReFRg2zCEhmfiNYR/oUYh/P8BVpb19XEMC1MWDz3oM2iV3CszRWrvgXe/u+RDU88/LI
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: redis-secret
      namespace: redis
