apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    strimzi.io/cluster: k3han-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
        class: local-nfs
  resources:
    requests:
      memory: 512Mi
      cpu: "250m"
    limits:
      memory: 1Gi
      cpu: "1000m"
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: chorde.io/tier
                    operator: In
                    values:
                      - medium
                  - key: chorde.io/region
                    operator: In
                    values:
                      - tw
