nodeSelector:
  chorde.io/tier: low

tolerations:
  - key: chorde.io/purpose
    operator: Equal
    value: proxy-only
    effect: NoSchedule

metrics:
  enabled: false

serviceMonitor:
  enabled: false

dashboards:
  enabled: false

config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server  On

  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Name k8s-tag-parser
        Format regex
        # 修正 Regex：直接匹配為 namespace, pod, container
        Regex ^(?<pod>[^_]+)_(?<namespace>[^_]+)_(?<container>.+)-(?<docker_id>[a-z0-9]{64})\.log$

  inputs: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Regex_Parser        k8s-tag-parser
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Buffer_Size         32k

  outputs: |
    [OUTPUT]
        Name        loki
        Match       *
        Host        loki.loki.svc.cluster.local
        Port        3100
        Labels      job=fluent-bit
        Label_Keys  $kubernetes['namespace'], $kubernetes['pod'], $kubernetes['container']
        Auto_Kubernetes_Labels on
