apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rebodutch/Chorde.git
    targetRevision: dev
    path: gitops/base/prometheus/charts/kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
        - ../../values-custom.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true