---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBlEIvzMGuXIML2k1yndaK/M1qbTiWwdkS7rahdBSIgs+0QMV6vHqdSAmlgQiY9Tney4tPKK7pZa0DwfOC0YziQ7OtuKWS85Wu2oTfPROPa38LfChuYB0Q/9BTGWWrxhT9LWWmQVThAiGPS82zIOxkwPd8Ok9SdlclPyQC4YZn+bdOAQoJfNX4g7CjCiT9Qx83FMNQAOXBPJ04mosdnAbBBE8uzsHQL4dSMMYu7vkJ5k5jLaqrus6sLLn0q5m6Ojdrvn6jIoDHgKng3nbvYnDDWWUIEwdC9h/jUKooIkKvsN0JCMBB7dYQNSAJ5BOpwK9f7I/O2WnOLictzuY3tHqH9VEw+RpYZtdoGCg/HqrQXTQ5x1oMSMcr0eOSSZjjbgFKyGzA4PPk0pTE6Tala/6LAmkdW0mUBzotUdSOC9nTjUIypxtigz/BBitPp678VssqZeCVoTAQ0g5lSX0EHYS47+VmoVLSXE+KYHMauJOJYAXeFXwXoGYYK5t36dtDPkrvgpRomFPr49wHW4x0+aRNl4XfkknGaLcwWERF06jpskkY3GrnKbLjv8SSFIxcszOJzRMfpIVT0Eb3BDqMz2I5/0bovT1BnKQrQlHIrO6gRsDNy4Oq8j6ofbmZ3ReKVN1IM2wjixK4+oQDH/KTI83pJJA2175QGINtUAKeYNElsUn2H4Pp+c2uei0rrkBqyNWbAZrlffP2hwuSjavPVHg==
    admin-user: AgBkGlt2a5S+LYjgUbdTi9o3H7466xyV+lOfzEgN0fdn2i397/FmbKiTdwHdFlt4Iv+k+IBUfmBM7xpFWKqvOh12u4TSrZgtS3gblTKNk5z6T9KrcV/DmPkTF0wU1rG3tdGx3XpUG7DJ6DyO3oeobalhZnCPLUmgdzeP/rmXnNn2D8BGznQ6KBN+t3TJoxeH8+FOm2wYO5NEwLTgAkFGiZmMfYurEyuuoh7eh4xpSidpas6f3kYBqHATc+tcgIZwJm0r5QuETeG+PHrIpMXUtz1vA61TcH3XqUdtIzetKJTNEdCk6rvSCb6sYoaEFbpJZi5VzHFzr6qC6ZK8r+LKtugotYAc3SwZpgUrZF1UTh4nE0FLfuaCerLifKOg7FvQzp9C//RBw6k2UfqAUhc4G2e3+HgO0span7QVFuBWgWXJ1PtFF3RtrGDXxeamorn950Owd/kgNk9DigXwDcBkKVSYj58/YQ/a+eGW0AZuMEbIkwR/xlM27bdUOXB+aKmeUsvYQTpHnod0gjjnjRHSgGc0o2XYtwAtK3StAIHXLvcJa14ie2f5JIEE5zMRGPeBWvh4hgHTZsGE/gCcUiRjT1YQnf2WN4U7YB51Bhn5fYmDtrnF0JVj+94qymclfoe3tLPZhR/fqaXJ89iTuhZzhweT5J6LBs58YfXyqdH2FJufVrC2pzwMzp+/WPbfxM087Hsq1IJC+ZkgNA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
