---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBYBulnzop4rxSLdHp+8XLhoZ2NgyBZlR2fsnhdOnK2vR+6SK8wUc9rjqlHRoMp+clZBOlomijMngAPwh6fIhQMdZcDS3PGLAh89WwQ9gKTUdkRgDpKYpkfzXASBxWqtjxwhRmccFJuzR3br2G4yWjYor6AhNNF5SYIsKApyLQGHrlzWG7q06diCF36IZkuHRYK4G8PyoJbEFo+PoRyCka93BD9MSuECMI0tZ1MTwpEP7LorzHjHscq29RjVEDqSBdL2gkrEIVCimrdSHPDiiXa/29MqULe1FGPkx/HAKRp09p9ehMN49JT4PNQ5FbWCP+R4+r602lIacUCctGlYSPifTdvk8NkfoYfiAbzlpiP3CGsxygFw0y4LImIEG4Zn5c7mQ60zQPA/pebqrourGgrXdJIpnbSLUtaI94pOGuysJOr05VlpRnIdki2Wvh5ohblVA+LlBTNA7PI5884MOqZg9JItvLVVkNE6XspCBzVPEev217zmTEhvS8ZlbPVT8OsZBzx8CKiTyITOZdWGWiwrZE42uLKGQ8eysRNuRyKQbBpJJVYK3zQDwgUM5GtyQjJJuxT9aX8SzP4gQBgyosh8MBCnMmpRT/xbKfkgWXRnUn6LjLNx0oRAiLMBFqjOkUPrXYWfl0TS9R6o0TiQqcbvWqWrKrGlSBBGHh1d1Onovg9XpA461M2R4IsDSbH2Lc7GpgDampjkz3kRzg9bRU=
    admin-user: AgBuyWjJ6Ab/n+AMaJ1t1xpcmENSubgSfl/2rUgdMXmVRYU1SpvKznMqYOortiM3yV1+wLuclPa9SMORcFc1TZoaw7UpqB+cDFOmim9G3QA4OHqIeRG9hzFmH52YFGcqthCS457836WEn0dDS/xMQ2Rz55JxyaF8KKR+egxJ9Y1xzuBe3U5HeHixOgr8JK7KABp1W4Pss4yz0uBvQU+ol8kKWaeK157r+odwNM7vOLVrMlJkTHYY6QWaCmFjtAOOLxOagPvgRNqgAGcPQ7DeQdNMm1sg0kaRs0EpNqdoV+BgC8gYdBFGF6p92Jx6cDwa2AbwWBD5MuCsSwnyOPTNUAozGSfh856WwthwTOypyWa3jJj2Imo8c2Fztkn6Oh+E2EFR7hQ+ejdfMfJ5xz/cMFq4SwnMhcwi0BzxH/w/B2U2Xc7HvVx/tLQPJ3dxZB3oyvJrvK8KXRfXGEIrEMleeHieIDbQKpzJDaq4JKiZDi8ZnIo3JrJudumzL9agQaSMgReKpG+RtAnJFbhgde+YYVOve5gUcYQ9UY7sdk9IXWiIZYwVsP8nHjTYBxAt5TM/qC99FrbRUWNrQosrxZ+OwhVA4JQFGexQ3wwM0g+FFlDhSR8IYruE0Sg8sNfPjIOLYF/p2M7gBKaos7X9d+KKQFw+vs+wyngOWcDeEMdlheDx/fGOClisSE0RhCAvHK8ByFGEZgmoEJhQy4Q=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
