apiVersion: v1
kind: PersistentVolume
metadata:
  name: contabo-local-10g-prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path 
  local:
    path: /mnt/k3han-pv/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists