---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgCUmyaT72OgfSykt8FZCwLxdqkz65KyYC9MQ8spzjxkbRq4Hhr0sU+I+9nz0s1uMZE7nyg5LxvwkRmsEA3ojvuTk/TtdtY0g0PhsXsuXB2PUjMIO10jmjgC/Ty9HKc5cBRCWYAEBlMOhowGqfpsOtHpEHsWd1FVyj71VMjPJ2HOPyFeMMx3rrzlBUUfa9FNDagMLbdWPjKnu3kTjIlIQdS5ocJMGe49jbsVV50/bEfj0arews2JsQ5sFGhSvKiofa847K1EJzopyWalDeJy6hM2bsqGSDmHzRixlPeUFDe6bioz8vuVdcdr7RYfWKs34aWX1PMozTZn+MHdGRcujpNxYdJp2nvUIafamhVdRe/ACG+HtUSKsRPy4FGp2hmSMd/aaca+hDDSvXpkWyOwJlim27Dauil6b8kv0JXFbwoNLM9befvg0HZyl5j7U7AV/kPu/8+cn9QpPpTnT6Nrou6CfKOYoGmAWcbqjN3Kz9KFOQB1gfqADpVQ9nqblJ1f417190aO/nyicCIwRGX80jgaPj1jWkeT8WQVVJw4vWpW8aQwXsSlgt6FZKbzbTPIv7zBibyoDV7zBCc39LTCb9sGqooia8urmzxz6Qy85GmcCEsTFnwjJDofWMEVi1lhI1bPq6i1LjuPg8ZJccz2/URNSE9iX12rB8V21AkqPMKBMHkpY/tNvNLx7MGr7YO0wJFv7y0eLDk=
    passwordKey: AgA42iGZpzUnuJ2XWvohvu3AHlCya+UTXpxS5o+Ycsc+utTC5+DAdH2IFZIuINK90WpPKOIHFrF0uhoOMgr+mJh3vK0VELmV9WpdbMjczbqi8V7fBeNrtnC1epPrkE+c5CdyEgvdfnAwm9VwrkI+w6lD7zkDzgqaSSi+yyigl+SHImKoXe5cUT23o5+KBkI6RdOYttplpjjqn6WZlx53A9C8J38x8ZXkRZj2L5S9tscA1SYx27i17QoTwFgqPIzklQZeeOZx9/y36tRp2e7xQZxnZ4jx6OLyBqFUO7ZnrFZBO4jmL+ACRw53YivdTILt6DXbVDsUJ2Hg7iHts6ak9QMh9mQ0669olR4t9mXKLgC43TZx5kqIfOy+1xgHfBvdDF37mdq7Hm2FHrkXJeSssveqdS4xqBLvfricZnyc27FnawNbIzn2x5t1O5AH+plWDrD40BRagfDDy3uxBnvJ+h6/z22bLAdVsatvMuBf2B+ffIB8yBCbUM0F76NYnG10J+1tU3WVixQstBOBovepXWt9Ab20IL+ClyDYps9HIxTTR1++WCvc7C1aM+8G7RfAsKQ6QFnXfC7iMOne3XvZslNMMTf/LKgDJxJjNMw0E36a/PbXbqrcKjDovpunz7KHRnQxwI2XU8KJmnX8tZwuMrTuSh7loWUW0Nr5bwHzfYdJ7xnSgphFsItoQcN/Q/siSGTYMKTRHtxdN3rTXqdnuk4=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
