---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCwsbuAxJRzjlemaDjCP2NMvhjsbmzS0eVPzMR0lLKg4ibBXrwee6fW1OvS0FemQiiyGwAD3nKcSXWaHihk4wFETuvi8jKAVxnS6sU6fujixU+le+RrXDQhHQVKhgMis5Wva23gt+0wosC+A1PiTnnMBZe5lQ7Be3VsdNSteHH2KORf2QfyjM6GeqisQ19Xn8OJo8qjtUwdMEyrlMac4srK9CcWt3hk4mEi7oo98OqLLeHZzJW6j20SQr99imMkM3i8HAWscpX2U1yc272pmEJY/cicxDXRoD33xOxXYWHXaPHgtL4u8i6YDvI8J5FWCmPoL7oIa6SlpqNyviFB2pa9JsMOvye++js2JuO9XUg2GU8b39tkQYfXR3UaAM0HL42cfa0E7KDCECqoywqLJBQBn2QooEPdysPgnp6SMF2tZlc/5Sk3f9D9dliih4rSIIqnAXN88nzsNzYEIIV3vr4qaRW1gt2bsqHNvxIRkm2AQFPhGeHyLAY0jt5rrWuCRfRJLEw++9F1v/QH8K0qibLRXsAz3NXici3loy+AOik4H1VAy4umv44Y3Y0dnE29yyLTlbyOnciudoIVSDDpU6femCm+AX+uW3bXl4SkrEjeoyj83fxGPmwDMCcfo3j89C/T90HdOIlZyvxJieD/hRBCsSGBomIIKYztcrYoOluWzBv12VvrL/IHAzsTn9BlgxOujD8zDpi/0wBOnMMm4g==
    admin-user: AgAzkciBACOCwktKTpC76gpGz7BmzDsG3/7CrPaGNDvZH2F8DY25bmKR3+FIXSbGck5NkKi5UR5nLoekEry8nDtAYlEPL2i7XbPBCHLXc2UffSgTBqHgLbH83Mm2ZFWKFcacPqg+HhgWQ/74doKQLp3+S9v6d8xP0vGUUd9c7bIRx8KtX4UIMxVkBfQzIqCXclMzjD5SPUpV0MeGguHPCpm6jSRZALMPpDeytvQFczqpPC8g1M7Q93nLcwix9tI4oDjqwsWpasdxyKpmV/Z5Ty0xvnct+b0aWq1M7N1PLf1BuTPx29gxdzdley0iMOxuMNyaQ9rrJRfqe878X6fEITLdlUbrFtbpG/hG8pvkMQdBTMUSFNZnlMcCrA1k3pv+C64Vvt52KBkGROMHYi8xJJBEqi56iU8bN6sdQ171SYgMbd/JrKDRdsLWDfMqt+RPtk2c6hp2gs5divNeGOYpsqA7owZ4ESMUALBqo3UDjvJC9JVKJ+loS1LLMtRrxhLJrJKjkv7RN/5TnRkPzVX/6hxfBeCHLHvHAs0C9AvexAB0xl+Znrw9lxFj/ZH+gJyw+xfxc+/yjVY4Y2eSq5jRNq38XKoUA47ULmc3j+ApRnd468gOIJmNbqc5K4X+FynN1/sIzu2rhH8rEj3Yy+3Uu28usFvYC/wSGMX9+9hmRf0qdsUoCKoZF1FYvYIFAoICo4Cu1jIz2oabGg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
