# tou have to change architecture to replication if you want at least one replica
# standlone or replication
architecture: replication

primary:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/tier
                operator: In
                values:
                  - medium
              - key: chorde.io/provider
                operator: NotIn
                values:
                  - local
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  persistence:
    enabled: true
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

readReplicas:
  enabled: true
  replicaCount: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: chorde.io/tier
                operator: In
                values:
                  - medium
              - key: chorde.io/region
                operator: In
                values:
                  - tw
  tolerations:
    - key: chorde.io/provider
      operator: Equal
      value: local            
      effect: PreferNoSchedule 

  persistence:
    enabled: true
    storageClass: local-nfs
    accessModes:
      - ReadWriteOnce
    size: 5Gi

auth:
  existingSecret: postgredb-secret
