auth:
    postgresPassword: ENC[AES256_GCM,data:uk3Oc2XFNFx/kII=,iv:XInmWGwxPa6HSvhzbCcgEbmuzGuivlLXwgRNMVz5WGc=,tag:Xasl2q5ZxpgFNwLdd94oXA==,type:str]
    replicationPassword: ENC[AES256_GCM,data:MEBTsxEXQp/fvHs=,iv:SKYkXkzl5d7j+juamMAzYgk+NXtagZMmtx1uW0yzLW0=,tag:7cp4MNwkKFP54LlfUzHeHQ==,type:str]
tls:
    enabled: ENC[AES256_GCM,data:HdUblTA=,iv:/G9NCVrC39SKCoUZUUly9ZQ5eL9X1bkI59K5h7SRqGM=,tag:YH9oOz7VtNf8MOdpgigjOA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-04T08:52:10Z"
    mac: ENC[AES256_GCM,data:MCpvo/BKKbEuml8C8EbARP/JQ/qdRvGwvAh3GUQxAQRVYC+fw3DluEm/2dQzpkl2xUX756x59Mq8YzgT7JfDtK3/9hNHwuStKRF3Dpp6+ZgjlnC6lqF47LfYjBeHTjLn0BICGtkinE3ynUN06azmfke0lKtfiimA7fok1qL1kMc=,iv:RaZPeIhKhq8fWiKFXHjqAKzcn2QDMXTeBIxexfBmQIE=,tag:F4McpkU4o6tm5Tm5f8DsPg==,type:str]
    pgp:
        - created_at: "2025-03-04T08:52:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+YWwbVhnjjMARAA2XmTLxBRAIO1ZQFEyigzkQg7iqCJ61GkOG/jwFk5I7lO
            rB2Bo+bmahVGvRtexWma7HHb/wQXjb5GM0D6oahFDQ/GZIk5bFQR0wI4jPK/9Dx8
            0GQpXlXNqgeQnEeu/VrVhLIcaha2ul76LN8CzsbomHMUyaR/u7FY29TQo5XGaI30
            2WEdV4UanJy5FMq3UX11iBER8qN/E51M2okA5F5Jt87MDTRpWbfUZa0aMkpeioDK
            lrOXfU8Iixwk4MHA3Blw5aX2YRWtlPS+KojJYqzHfWtupry1M4IXJ5zBTpXxlCkv
            KiJeO04W0X3Ml1o27PmLW5r4fiX7A+G6Bf7VgVBL54s2YHzY/S5Az3tYIC89Quyt
            nIthRMpRX4P+swVt6Fz9pWSGmnh+dD5Wr+lVD9dJImj6Qqn59h9LmCLceWwMjFtu
            9/m48n6PcR7D0taJj3wTtbjJM54dVOt8JbcivjE5N1AXg06GAIbt+XASQuS6BCjo
            yxMwdlI49PZkCtgYg/ag84nOd0w230oUQpl/P6xeZD1igxUE/5A1+XdvX+/FKV9+
            sBV8j+QcXvgBR/mg1tlFwMrFdGUTO+2WX5ske7bI0dtfGTnxQ+R04VL2AEfFN6lv
            uteyDMMrUsb98V/GA0rQVpQ6dBfkx/tmMQhRuqfaDmTHsQD2kgKuNcVCHFaHf5TU
            aAEJAhC+MZzSM7VTzXRr4rHhxQR/eDCkq/5+vnm0kBvUWLVx5FLQON6rGGmJPSdy
            Wqa4Y2k3bhQs7RsocyS9oO+t+rzooJJjy6zcJsjknFc+wdWCEGdFngDSwxmlJtmB
            F57ioxTE/iPi
            =1wuO
            -----END PGP MESSAGE-----
          fp: 720C9A840B613F4DC238F7300F7FB46874E473BD
    unencrypted_suffix: _unencrypted
    version: 3.9.4
