# tou have to change architecture to replication if you want at least one replica
# standlone or replication
architecture: replication

primary:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/db-primary
                operator: In
                values:
                  - "true"
                  
readReplicas:
  enabled: true
  replicaCount: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/db-replica
                operator: In
                values:
                  - "true"
# if no user be set, the default user (postgres) will be used
auth:
  existingSecret: postgredb-secret