architecture: replication

primary:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/db-primary
                operator: In
                values:
                  - "true"

readReplicas:
  enabled: true
  replicaCount: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/db-replica
                operator: In
                values:
                  - "true"

auth:
  existingSecret: postgredb-secret